### ISSUE TITLE
Follow the steps and contribute in Hacktoberfest 2021

### ISSUE THREAD

**Issue by anupam-kumar-krishnan** [anupam-kumar-krishnan/Competitive---Programming-DSA-450#18]
# 🚀 _Steps to contribute_

### <b>_4. Make a PR🔁_</b>

# 📌 _Please Note:_
## 📌📌 _Note: Only one PR allowed per user_

**Comment by Akhilesh0947** [comment]
please assign this to me

**Comment by anupam-kumar-krishnan** [comment]
Go ahead🚀

**Comment by Shrishti-2002** [comment]
Please assign this to me.

**Comment by anupam-kumar-krishnan** [comment]
Go Ahead🚀

**Comment by abhijeet-crypto** [comment]
please assign to me @anupam-kumar-krishnan

**Comment by anupam-kumar-krishnan** [comment]
Go ahead🚀

**Comment by deepvasan02** [comment]
Please assign it to me @anupam-kumar-krishnan

**Comment by anupam-kumar-krishnan** [comment]
There you go🚀

**Comment by anupam-kumar-krishnan** [comment]
@abhijeet-crypto done🙌

**Comment by anupam-kumar-krishnan** [comment]
Go ahead🚀

**Comment by Nupurgit2000** [comment]
I have created a pull request, please review it.

**Comment by anupam-kumar-krishnan** [comment]
Sure, go ahead🚀

**Comment by SanjanaPurbia** [comment]
Can I work on this issue

**Comment by SanjanaPurbia** [comment]
Can I work on this issue? I am a beginner and learning how to contribute to open-source

**Comment by sejalsingh417** [comment]
please assign me

**Comment by nikhil822** [comment]
please assign this issue to me

**Comment by nikhil822** [comment]
please review the pull request @anupam-kumar-krishnan #157

**Comment by anupam-kumar-krishnan** [comment]
done🚀 @nikhil822

**Comment by KhushiN893** [comment]
@anupam-kumar-krishnan  I have created a pull request, please review it.

**Comment by Akaxh** [comment]
Sir, please assign it to me

**Comment by anupam-kumar-krishnan** [comment]
go ahead buddy🚀🙌

**Comment by PreetiBaskey** [comment]
hey @anupam-kumar-krishnan, i want to contribute in this issue. Kindly assign me this issue.
Thank You.

**Comment by Ruturaj-7802** [comment]
please assign me this issue @anupam-kumar-krishnan

**Comment by anupam-kumar-krishnan** [comment]
Thank you for participating in hacktoberfest 2021🎃
