### ISSUE TITLE
Adding code to implenet BST in c++

### ISSUE THREAD

**Issue by tanvinimbalkar** [anupam-kumar-krishnan/Competitive---Programming-DSA-450#79]
Can I work on this issue?

**Comment by anupam-kumar-krishnan** [comment]
it is already there 
add any code except this one

**Comment by anupam-kumar-krishnan** [comment]
I'm closing this issue 
You can go ahead and add any code just check that must not be present
And make a PR
That's it✨🚀
Thank you
